--
-- RagnarokOnline Settings File
-- Generated by RagnarokOnline OpenSetup, Version 2.11.5.396 ( http://ai4rei.net/p/opensetup )
--

-- Workaround for people with broken client folder
-- Note: The client removes this when it saves settings.
--
if OptionInfoList==nil then
	OptionInfoList = {}
end
if CmdOnOffList==nil then
	CmdOnOffList = {}
end
-- End of Workaround


-- Settings
--

OptionInfoList["Trilinear"] = 0
OptionInfoList["Bgm_Volume"] = 100
OptionInfoList["Effect_Volume"] = 100
OptionInfoList["MouseExclusive"] = 0
OptionInfoList["ISFULLSCREENMODE"] = 0
OptionInfoList["WIDTH"] = 1024
OptionInfoList["HEIGHT"] = 768
OptionInfoList["BITPERPIXEL"] = 32
OptionInfoList["DEVICECNT"] = 0
OptionInfoList["MODECNT"] = 4
OptionInfoList["SPRITEMODE"] = 2
OptionInfoList["TEXTUREMODE"] = 2
CmdOnOffList["/bgm"] = 1
CmdOnOffList["/sound"] = 1
CmdOnOffList["/notrade"] = 0
CmdOnOffList["/noshift"] = 0
CmdOnOffList["/noctrl"] = 1
CmdOnOffList["/skillfail"] = 1
CmdOnOffList["/notalkmsg"] = 0
CmdOnOffList["/notalkmsg2"] = 0
CmdOnOffList["/showname"] = 1
CmdOnOffList["/fog"] = 1
CmdOnOffList["/aura"] = 1
CmdOnOffList["/window"] = 0
CmdOnOffList["/miss"] = 1
CmdOnOffList["/effect"] = 1
CmdOnOffList["/shopping"] = 1
CmdOnOffList["/stateinfo"] = 1
CmdOnOffList["/loginout"] = 1
CmdOnOffList["/snap"] = 0
CmdOnOffList["/itemsnap"] = 0
CmdOnOffList["/skillsnap"] = 1
CmdOnOffList["/camera"] = 0
CmdOnOffList["/hoai"] = 0
CmdOnOffList["/merai"] = 0
CmdOnOffList["/lightmap"] = 1
CmdOnOffList["/monsterhp"] = 1
CmdOnOffList["/q1"] = 0
CmdOnOffList["/q2"] = 0

-- Preserved client settings
--

OptionInfoList["PlaySound_Open1to1Window"] = 1
OptionInfoList["ChangeChatMode"] = 1
OptionInfoList["ShowBattleFieldIcon"] = 1
OptionInfoList["Show_SkillDescript"] = 1
OptionInfoList["AutoOpen1to1Window"] = 1
OptionInfoList["bLockItemDropFromItemWnd"] = 0
OptionInfoList["AutoOpen1to1Window_Friend"] = 1
OptionInfoList["Indoor_ViewLatitude"] = -55
OptionInfoList["LockMouse"] = 0
OptionInfoList["bSoundEffectInItemSellWnd"] = 0
OptionInfoList["Simplicity_SkillList"] = 0
OptionInfoList["Window_YPos"] = 79
OptionInfoList["Outdoor_ViewDistance"] = 400
OptionInfoList["SkinName"] = "<Basic Skin>"
OptionInfoList["ChannelCopID"] = 0
OptionInfoList["Window_XPos"] = 144
OptionInfoList["Outdoor_ViewLatitude"] = -65
OptionInfoList["Indoor_ViewDistance"] = 300
OptionInfoList["bWarningPriceCheck"] = 0
CmdOnOffList["/goldpc"] = 1
CmdOnOffList["/cashshop"] = 1
CmdOnOffList["/roulette"] = 1
CmdOnOffList["/quake"] = 1
